name: Release Model Service Image

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set IMAGE and TAG env vars
        run: |
          TAG="${GITHUB_REF#refs/tags/v}"
          IMAGE="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}"
          IMAGE="${IMAGE,,}"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "TAG=$TAG"   >> $GITHUB_ENV

      - name: Build multi-arch Docker image
        run: |
          docker buildx create --use
          docker buildx build             --platform linux/amd64,linux/arm64             --tag $IMAGE:$TAG             --push .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.TAG }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
